describe('PlanetScreen', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })
  it('should be open planet screen, click refresh profile, show title and return home', () => {
    cy.contains('button', 'About us').should('exist')
    cy.wait(2000)
    cy.contains('button', 'About us').click()
    cy.contains('button', 'Refresh Profile').should('exist')
    cy.wait(2000)
    cy.contains('button', 'Refresh Profile').click()
    cy.wait(4000)
    cy.contains('button', 'Refresh Profile').click()
    cy.wait(2000)
    cy.contains('button', 'Show It').click()
    cy.wait(2000)
    cy.contains(' Return Home ').click()
    cy.wait(2000)
  })
  it('should render about us screen, click to show details, redirect to dynamic screen and test it', () => {
    cy.contains('button', 'About us').should('exist')
    cy.wait(2000)
    cy.contains('button', 'About us').click()
    cy.wait(2000)
    cy.get('[data-testid="buttonDetails"]').eq(2).should('exist')
    cy.wait(2000)
    cy.get('[data-testid="buttonDetails"]').eq(2).click()
    cy.contains('p', ' name: ').should('exist')
    cy.contains('p', ' email: ').should('exist')
    cy.contains('p', ' phone: ').should('exist')
    // test for userId
    cy.contains('p', 'For USERID').should('exist')
    cy.get('p').should('contain', 'UserId: 3')
    cy.contains('button', '+').should('exist')
    cy.wait(2000)
    cy.contains('button', '+').click()
    cy.wait(2000)
    cy.get('p').should('contain', 'UserId: 4')
    cy.wait(2000)
    cy.contains('p', 'Update').click()
    cy.wait(2000)
    cy.contains('button', '-').click()
    cy.wait(2000)
    cy.contains('button', '-').click()
    cy.wait(2000)
    cy.get('p').should('contain', 'UserId: 2')
    cy.wait(2000)
    cy.contains('p', 'Update').click()
    // test for counter
    cy.contains('p', 'for counter').should('exist')
    cy.get('p').should('contain', 'Counter: 2')
    cy.contains('[data-testid="+"]', '+').should('exist')
    cy.wait(2000)
    cy.get('p').should('contain', 'Counter: 2')
    cy.wait(2000)
    cy.contains('[data-testid="update"]', 'Update').click()
    cy.wait(2000)
    cy.contains('[data-testid="-"]', '-').click()
    cy.wait(2000)
    cy.get('p').should('contain', 'Counter: 1')
    cy.wait(2000)
    cy.contains('[data-testid="update"]', 'Update').click()
    cy.wait(2000)
    cy.contains('button', '-').should('not.be.enabled')
    cy.contains('[data-testid="-"]', '-').should('not.be.enabled')
    cy.wait(3000)
    cy.contains('About Us').click()
  })
})
